### ISSUE TITLE
Can't Start Bot

### ISSUE THREAD

**Issue by voltrare** [Killerpac/Discord-24-7-Bot#1]
Im using repl.it to run this bot
I have added the bot with `bot` and `application.commands` with `Administrator` permission

heres the problem 

``` 
> nino@2.1.6 start
> node src/index.js

Logged in Successfully
Started refreshing application [/] commands.
DiscordAPIError[50035]: Invalid Form Body
application_id[NUMBER_TYPE_COERCE]: Value "undefined" is not snowflake.
    at SequentialHandler.runRequest (/home/runner/Discord-24-7-Bot/node_modules/@discordjs/rest/dist/lib/handlers/SequentialHandler.js:198:23)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async SequentialHandler.queueRequest (/home/runner/Discord-24-7-Bot/node_modules/@discordjs/rest/dist/lib/handlers/SequentialHandler.js:99:20)
    at async /home/runner/Discord-24-7-Bot/src/reload.js:24:5 {
  rawError: {
    code: 50035,
    errors: { application_id: [Object] },
    message: 'Invalid Form Body'
  },
  code: 50035,
  status: 400,
  method: 'put',
  url: 'https://discord.com/api/v9/applications/undefined/commands'
}
Error [DISALLOWED_INTENTS]: Privileged intent provided is not enabled or whitelisted.
    at WebSocketManager.createShards (/home/runner/Discord-24-7-Bot/node_modules/discord.js/src/client/websocket/WebSocketManager.js:249:15)
    at async Client.login (/home/runner/Discord-24-7-Bot/node_modules/discord.js/src/client/Client.js:245:7) {
  [Symbol(code)]: 'DISALLOWED_INTENTS'
} Promise {
  <rejected> Error [DISALLOWED_INTENTS]: Privileged intent provided is not enabled or whitelisted.
      at WebSocketManager.createShards (/home/runner/Discord-24-7-Bot/node_modules/discord.js/src/client/websocket/WebSocketManager.js:249:15)
      at async Client.login (/home/runner/Discord-24-7-Bot/node_modules/discord.js/src/client/Client.js:245:7) {
    [Symbol(code)]: 'DISALLOWED_INTENTS'
  }
}```

**Comment by sanicxt** [comment]
Replit won't run the bot correctly as it runs on discord js 13 which requires node 16.replit has node 14 I think.

And I think you don't have privileged intends allowed in bot settings

**Comment by voltrare** [comment]
> Replit won't run the bot correctly as it runs on discord js 13 which requires node 16.replit has node 14 I think.
 
i have used the nix thing to get it using node 16
> And I think you don't have privileged intends allowed in bot settings

true i just realised this also 

thanks for the bot tho
